### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by KingSpidey91** [Synthlight/Nexomon-Extinction-Save-Editor#12]
I've been trying to get the program to run for my PS5. I've extracted the files and once I click on the program it ask what file. I select my file and noting happens. I found an EU save online that was dated 9/16/2020 and the program worked flawlessly. I'm not sure what it could be at this point. I even converted the EU save that worked before to USA through save wizard. I transferred the converted save to my console and all the alterations I made with the SE worked. I transferred back to my PC and the program won't open again. What could I be dong wrong.

**Comment by KingSpidey91** [comment]
[memory.zip](https://github.com/Synthlight/Nexomon-Extinction-Save-Editor/files/9376370/memory.zip)

**Comment by Synthlight** [comment]
This save is absolutely tiny, like, new-game with almost no ~~pokemon~~ nexomon tiny.
If this sounds wrong, well, I dunno, but the size doesn't lie.

It's never been tried with a ps5, only a ps4. I know the game on Steam has been updated since and I've kept it up-to-date for that.
It's quite possible that the ps5 save is a different format or has been updated since.

> I found an EU save online that was dated 9/16/2020
Well, yea. That was before the expansion. Expansions need save migrations, ergo things have changed since.

I'll take a look when I get home later and see if I spot anything that needs updating.

**Comment by KingSpidey91** [comment]
It is a new game. I started today. How would I increase my fie size for the SE to work?

**Comment by KingSpidey91** [comment]
The version of Nexomon is the PS4

**Comment by KingSpidey91** [comment]
The EU save I was testing on had a bigger file size when I was able to get the SE to work for me. However, once I converted the save over US it had the same size but didn't work. Thank you for the prompt response.

**Comment by Synthlight** [comment]
> It is a new game. I started today. How would I increase my fie size for the SE to work?

That's not how this works. I'll need to fix whatever issue is preventing it from reading a nearly empty save.
It isn't something you just 'increase'.

> However, once I converted the save over US it had the same size but didn't work.

Region should have zero bearing on this. The save is literally the same format no matter what country your run the game in.
The PS4/5 might add something like this, but it shouldn't change the structure.

**Comment by KingSpidey91** [comment]
Okay, I'll wait for you to let me know how to proceed.

**Comment by KingSpidey91** [comment]
I don't know if this will help, but I did notice when I'm transferring from my console to USB, the file is 39MB. But when I export that same file from sav wizard it decreases the size of the file to what I sent you.

**Comment by Synthlight** [comment]
Keep in mind, I only own this on Steam and can't guarantee support on other platforms. PS4 support if finicky at best since I rely on people giving me saves that don't work. I can't test editing them, only making sure they load/save.

So there's technically two save slots in use here, one which is the 'TOP' slot and a second which is listed first, but isn't really a save.
It *looks* like a save in the file but it's contents are literally `dSvDvhofwqbDmg==`.

This looks more like some checksum, something base64 encoded or something. I don't know what/why it exists, and don't know the ramifications of ignoring it. This **is a PS4 specific thing** and I can only guess at it.

Try this and let me know if it works.
[Publish.zip](https://github.com/Synthlight/Nexomon-Extinction-Save-Editor/files/9378141/Publish.zip)

**Comment by KingSpidey91** [comment]
It works!

**Comment by KingSpidey91** [comment]
If I edit the level will the SE know to add the moves if any are supposed to be learned?

**Comment by Synthlight** [comment]
You'll have to try and see what happens.

Fixed in v1.6.1.0.
